version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
            - maven-repo-v1-{{ .Branch }}-
            - maven-repo-v1-
      - run:
          name: Build the Package
          command: mvn package
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
      - run:
          name: Delete Build Cache
          command: |
            cd ./target
            rm -rf `ls | grep -v .jar`
            rm -rf `ls | grep .original`
            cd ..
      - persist_to_workspace:
          root: ./
          paths:
            - target/
      - store_artifacts:
          path: ./target

  test:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
            - maven-repo-v1-{{ .Branch }}-
            - maven-repo-v1-
      - run:
          name: Run Maven Test
          command: mvn test
      - store_test_results:
          path: ./target/surefire-reports

  push:
    machine:
      true
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: Login Docker Hub
          command: echo ${DOCKER_HUB_PASSWORD} | docker login -u ${DOCKER_HUB_ID} --password-stdin
      - run:
          name: Build Docker Image
          command: docker build --tag ${DOCKER_HUB_ID}/iter:1.0 .
      - run:
          name: Push to Docker Hub
          command: docker push ${DOCKER_HUB_ID}/iter:1.0
  deploy:
    docker:
      - image: shin6949/kubectl
    steps:
      - run:
          name: Set KUBECONFIG
          command: |
            if [ -n "${KUBECONFIG_DATA}" ]; then
              mkdir -p $HOME/.kube
              echo -n "${KUBECONFIG_DATA}" | base64 --decode > $HOME/.kube/config
            fi
      - run:
          name: Restart WAS Deployment
          command: kubectl rollout restart deployment iter-app

workflows:
  version: 2
  workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - push:
          requires:
            - build
            - test
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - build
            - test
            - push
          filters:
            branches:
              only:
                - master