version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:11-jdk
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
            - maven-repo-v1-{{ .Branch }}-
            - maven-repo-v1-
      - run:
          name: Build the Package
          command: mvn package
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ .Branch }}-{{ checksum "pom.xml" }}
      - persist_to_workspace:
          root: ./
          paths:
            - target/

  test:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ./target
      - run:
          name: Run Maven Test
          command: mvn test

  deploy:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - attach_workspace:
          at: ./target
      - run:
          name: Build Docker Image
          command: docker build --tag shin6949/iter:1.0 .
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run:
          name: Login Docker Hub
          command: echo ${DOCKER_HUB_PASSWORD} | docker login -u ${DOCKER_HUB_ID} --password-stdin
      - run:
          name: Push to Docker Hub
          command: docker push shin6949/iter:1.0
workflows:
  version: 2
  workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - build