version: 2.1
orbs:
  kublr-api: kublr/kublr-api@dev
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
            - maven-repo-v1-{{ .Branch }}-
            - maven-repo-v1-
      - run:
          name: Build the Package
          command: mvn package
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
      - persist_to_workspace:
          root: ./
          paths:
            - target/
      - store_artifacts:
          path: ./target

  test:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
            - maven-repo-v1-{{ .Branch }}-
            - maven-repo-v1-
      - run:
          name: Run Maven Test
          command: mvn test
      - store_test_results:
          path: ./target/surefire-reports

  push:
    machine:
      true
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: Login Docker Hub
          command: echo ${DOCKER_HUB_PASSWORD} | docker login -u ${DOCKER_HUB_ID} --password-stdin
      - run:
          name: Build Docker Image
          command: docker build --tag ${DOCKER_HUB_ID}/iter:1.0 .
      - run:
          name: Push to Docker Hub
          command: docker push ${DOCKER_HUB_ID}/iter:1.0
    deploy:
      docker:
        - image: 'cimg/base:stable'
      step:
        - kublr-api/auth
            kublr-endpoint: ${KUBLR_ENDPOINT}
            kublr-username: ${KUBLR_USERNAME}
            kublr-password: ${KUBLR_PASSWORD}
            kublr-token: ${KUBLR_TOKEN}
        - kublr-api/get-cluster-config
            kublr-space: ${KUBLR_SPACE}
            kublr-cluster: ${KUBLR_CLUSTER}
        - run: |
            echo "Kubernetes config in '${KUBECONFIG:-}' file:"
            cat "${KUBECONFIG:-}"
        - run:
            name: Setup kubectl
            command: >-
              curl
              https://storage.googleapis.com/kubernetes-release/release/v1.10.7/bin/linux/amd64/kubectl
              > kubectl && chmod a+x kubectl
        - run:
            name: Test kubectl with kubeconfig
            command: ./kubectl get nodes
workflows:
  version: 2
  workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - push:
          requires:
            - build
            - test
      - deploy:
          requires:
            - build
            - test
            - push