version: 2.1
orbs:
  kubernetes: circleci/kubernetes@0.12.0
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
            - maven-repo-v1-{{ .Branch }}-
            - maven-repo-v1-
      - run:
          name: Build the Package
          command: mvn package
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
      - persist_to_workspace:
          root: ./
          paths:
            - target/
      - store_artifacts:
          path: ./target

  test:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
            - maven-repo-v1-{{ .Branch }}-
            - maven-repo-v1-
      - run:
          name: Run Maven Test
          command: mvn test
      - store_test_results:
          path: ./target/surefire-reports

  push:
    machine:
      true
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: Login Docker Hub
          command: echo ${DOCKER_HUB_PASSWORD} | docker login -u ${DOCKER_HUB_ID} --password-stdin
      - run:
          name: Build Docker Image
          command: docker build --tag ${DOCKER_HUB_ID}/iter:1.0 .
      - run:
          name: Push to Docker Hub
          command: docker push ${DOCKER_HUB_ID}/iter:1.0
  deploy:
    machine:
      true
    steps:
      - kubernetes/install-kubectl
      - kubernetes/install-kubeconfig:
          kubeconfig: KUBECONFIG_DATA
      - run:
          name: TEST KUBECTL
          command: kubectl get pod
      - run:
          name: Restart WAS Deployment
          command: kubectl rollout restart deployment iter-app

workflows:
  version: 2
  workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - push:
          requires:
            - build
            - test
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - build
            - test
            - push
          filters:
            branches:
              only:
                - master