server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    
spring:
  datasource:
    driver-class-name : org.mariadb.jdbc.Driver
    url: jdbc:mariadb://{DATABASE_HOST}:3306/capstone?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: capstone
    password: {DATABASE_PASSWORD}
    hikari:
      connection-timeout: 59000
      max-lifetime: 59000

  # 스프링에서 머스태치 세션 적용하려면 필요
  mustache:
    expose-session-attributes: true
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
      
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      
  security:
    user:
      name: cos
      password: 1234

    oauth2:
      client:
        registration:
          facebook:
            client-id: {FACEBOOK_CLIENT_ID}
            client-secret: {FACEBOOK_CLIENT_SECRET}
            scope:
            - email
            - public_profile
            
cos:
  secret: {COS_SECRET}

file:
  path: upload/

azure:
  connect-string: {AZURE_BLOB_STORAGE_CONNECTION_STRING}