name: Docker Image Workflows
on:
  push:
    branches: [master]

jobs:
  image-build:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: iter-${{job.id}}
          path: ./target/

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: ./target/