name: Java CI with Maven

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v2.2.0
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Load Maven Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: iter-1.0.jar
          path: ./target/iter-*.jar

  test:
    runs-on: ubuntu-18.04
    needs: [ build ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v2.2.0
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Load Maven Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Test with Maven
        run: mvn test
        env:
          WEBAPP_PREFIX: ""
          DB_URL: ${{ secrets.DB_URL }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          FACEBOOK_CLIENT_ID: ${{ secrets.FACEBOOK_CLIENT_ID }}
          FACEBOOK_CLIENT_SECRET: ${{ secrets.FACEBOOK_CLIENT_SECRET }}
          COS_SECRET: ${{ secrets.COS_SECRET }}
          AZURE_CONNECT_STRING: ${{ secrets.AZURE_CONNECT_STRING }}

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: ./target/surefire-reports/*.xml

  image-build:
    runs-on: ubuntu-18.04
    needs: [build, test]

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_ID }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: iter-1.0.jar
          path: ./target

      - name: Docker Image Build
        run: docker build -t ${{ secrets.DOCKER_HUB_ID }}/iter:1.0 .

      - name: Image Push to DockerHub
        run: docker push ${{ secrets.DOCKER_HUB_ID }}/iter:1.0

  deploy-to-k8s:
    runs-on: ubuntu-18.04
    container: shin6949/kubectl:alpine
    needs: [ build, image-build ]

    steps:
      - name: Set KUBECONFIG
        run: mkdir -p $HOME/.kube && echo -n "${{ secrets.KUBECONFIG_DATA }}" | base64 --decode > $HOME/.kube/config

      - name: Restart WAS Deployment
        run: kubectl rollout restart deployment iter-app
