# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v2.2.0
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Load Maven Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: iter-1.0.jar
          path: ./target/iter-*.jar

  test:
    runs-on: ubuntu-18.04
    needs: [ build ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v2.2.0
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Load Maven Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Test with Maven
        run: mvn test

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: ./target/surefire-reports/*.xml

  image-build:
    runs-on: ubuntu-18.04
    needs: [build, test]

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_ID }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: iter-1.0.jar
          path: ./target

      - name: Display structure of downloaded files
        run: |
          pwd
          ls -R

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_HUB_ID }}/iter:1.0

  deploy-to-k8s:
    runs-on: ubuntu-18.04
    container: shin6949/kubectl:alpine
    needs: [ build, image-build ]

    steps:
      - name: Set KUBECONFIG
        run: |
          mkdir -p $HOME/.kube
          echo -n "${KUBECONFIG_DATA}" | base64 --decode > $HOME/.kube/config

      - name: Restart WAS Deployment
        run: kubectl rollout restart deployment iter-app